import Testing
import Foundation

/// What the head states about the page's own files and colours is true of them.
///
/// Three facts, each written twice in different places and joined by nothing:
/// the icon's sizes, the preview's dimensions, and the colour the browser paints
/// its chrome. All three are about things a person does not look at — a binary,
/// a rendered image, and a strip of window furniture — so a disagreement stays
/// quiet for as long as nobody thinks to check.
///
/// `<link rel="alternate icon" … sizes="16x16 32x32 48x48">` is a promise about
/// a binary that is generated by a script and never opened by a person. Both
/// halves are written by hand in different files: the sizes the script renders,
/// and the sizes the page declares. Nothing connected them, and a browser given
/// a size that is not there falls back on whatever it can find — quietly, which
/// is the only way anybody would ever have noticed.
@Suite struct TheHeadAndTheFilesAgree {

    @Test func theFileHoldsTheSizesThePageDeclares() throws {
        let declared = try Self.declaredSizes()
        #expect(!declared.isEmpty, "the page no longer declares any icon sizes")

        let present = try Self.sizesInTheIcon()
        #expect(present == declared, """
            favicon.ico holds \(present.sorted()) and the page declares \
            \(declared.sorted()) — a browser asking for a size that is not there \
            takes whichever it finds instead
            """)
    }

    /// The `sizes="16x16 32x32 48x48"` the page states, as a set of edges.
    private static func declaredSizes() throws -> Set<Int> {
        let page = try String(
            contentsOf: Self.root.appendingPathComponent("site/index.html"), encoding: .utf8
        )
        guard let match = page.range(of: #"sizes="[^"]+""#, options: .regularExpression)
        else { return [] }
        let value = page[match].dropFirst("sizes=\"".count).dropLast()
        return Set(value.split(separator: " ").compactMap { pair in
            pair.split(separator: "x").first.flatMap { Int($0) }
        })
    }

    /// An ICO is a six-byte header — reserved, type, count — then one sixteen-byte
    /// entry per image whose first two bytes are its width and height, with zero
    /// meaning 256.
    private static func sizesInTheIcon() throws -> Set<Int> {
        let data = try Data(contentsOf: Self.root.appendingPathComponent("site/favicon.ico"))
        #expect(data.count > 6, "favicon.ico is too short to be an icon")
        let bytes = [UInt8](data)

        let type = Int(bytes[2]) | Int(bytes[3]) << 8
        #expect(type == 1, "favicon.ico is not an icon: type \(type)")

        let count = Int(bytes[4]) | Int(bytes[5]) << 8
        #expect(count > 0, "favicon.ico declares no images")

        var found: Set<Int> = []
        for index in 0..<count {
            let entry = 6 + index * 16
            guard entry + 1 < bytes.count else { break }
            found.insert(bytes[entry] == 0 ? 256 : Int(bytes[entry]))
        }
        return found
    }

    /// `og:image:width` and `og:image:height` describe a PNG that is rendered by
    /// a script. A scraper that trusts the numbers lays out a card of that shape
    /// and then draws whatever arrives into it.
    @Test func thePreviewIsTheShapeTheHeadClaims() throws {
        let page = try String(
            contentsOf: Self.root.appendingPathComponent("site/index.html"), encoding: .utf8
        )
        let data = try Data(contentsOf: Self.root.appendingPathComponent("site/og.png"))
        let bytes = [UInt8](data)
        #expect(bytes.count > 24, "og.png is too short to be a PNG")

        // IHDR follows the eight-byte signature, a length and the chunk name;
        // width and height are big-endian at 16 and 20.
        func be32(_ at: Int) -> Int {
            (0..<4).reduce(0) { $0 << 8 | Int(bytes[at + $1]) }
        }
        let actual = (width: be32(16), height: be32(20))
        let declared = (
            width: Self.number(after: "og:image:width", in: page),
            height: Self.number(after: "og:image:height", in: page)
        )
        #expect(declared.width == actual.width && declared.height == actual.height, """
            og.png is \(actual.width)×\(actual.height) and the head says \
            \(declared.width ?? 0)×\(declared.height ?? 0)
            """)
    }

    /// `theme-color` is the page's background stated a second time, for the
    /// browser to paint around it. Two of them, one per scheme, against the two
    /// halves of `--ink`.
    @Test func theBrowserChromeIsTheColourOfThePage() throws {
        let page = try String(
            contentsOf: Self.root.appendingPathComponent("site/index.html"), encoding: .utf8
        )
        let ink = Self.matches(
            #"--ink:\s*light-dark\((#[0-9a-fA-F]{6}),\s*(#[0-9a-fA-F]{6})\)"#,
            in: page, groups: 2
        )
        #expect(ink.count == 1, "the page's background is no longer one light-dark pair")
        guard let pair = ink.first else { return }

        for (scheme, colour) in [("light", pair[0]), ("dark", pair[1])] {
            let declared = Self.matches(
                #"theme-color" content="(#[0-9a-fA-F]{6})" media="\(prefers-color-scheme: (\w+)\)""#,
                in: page, groups: 2
            ).first { $0[1] == scheme }?.first
            #expect(declared?.lowercased() == colour.lowercased(), """
                the \(scheme) theme-color is \(declared ?? "absent") and the page's \
                background in that scheme is \(colour)
                """)
        }
    }

    private static func number(after key: String, in page: String) -> Int? {
        let pattern = "\(key)\" content=\"([0-9]+)\""
        return matches(pattern, in: page, groups: 1).first.flatMap { Int($0[0]) }
    }

    private static func matches(
        _ pattern: String, in text: String, groups: Int
    ) -> [[String]] {
        guard let regex = try? NSRegularExpression(pattern: pattern) else { return [] }
        let range = NSRange(text.startIndex..., in: text)
        return regex.matches(in: text, range: range).map { match in
            (1...groups).compactMap { Range(match.range(at: $0), in: text).map { String(text[$0]) } }
        }
    }

    private static var root: URL {
        var url = URL(fileURLWithPath: #filePath)
        for _ in 0..<5 { url.deleteLastPathComponent() }
        return url
    }
}
